# Generated by Django 2.0.4 on 2018-05-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_licencia_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='licencia',
            name='telefono',
        ),
    ]
