# Generated by Django 2.0.4 on 2018-04-30 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses_proxima_verificacion', models.CharField(choices=[('Enero y febrero', 'Enero y febrero'), ('Febrero y marzo', 'Febrero y marzo'), ('Marzo y abril', 'Marzo y abril'), ('Abril y mayo', 'Abril y mayo'), ('Mayo y junio', 'Mayo y junio'), ('Junio y julio', 'Junio y julio'), ('Julio y agosto', 'Julio y agosto'), ('Agosto y septiembre', 'Agosto y septiembre'), ('Septiembre y octubre', 'Septiembre y octubre'), ('Octubre y noviembre', 'Octubre y noviembre'), ('Noviembre y diciembre', 'Noviembre y diciembre'), ('Diciembre y enero', 'Diciembre y enero')], max_length=25)),
                ('año_proxima_verificacion', models.IntegerField(choices=[(2017, '2017'), (2018, '2018')])),
                ('verificacion', models.FileField(upload_to='verificacion/%Y/%m/%d/')),
                ('tarjeta_circulacion', models.FileField(upload_to='circulacion/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validez', models.DateField()),
                ('numero_poliza', models.CharField(max_length=15)),
                ('iniciso', models.CharField(max_length=15)),
                ('poliza', models.FileField(upload_to='polizas/%Y/%m/%d/')),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Aseguradora')),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_serie',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='seguro',
            name='vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Vehiculo'),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Vehiculo'),
        ),
        migrations.AddField(
            model_name='aseguradora',
            name='Nombre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Vehiculo'),
        ),
    ]
