# Generated by Django 2.0.4 on 2018-04-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_auto_20180430_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='año_proxima_verificacion',
            field=models.IntegerField(choices=[(2017, '2017'), (2018, '2018'), (2019, '2019')]),
        ),
    ]
