# Generated by Django 2.0.4 on 2018-04-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_auto_20180430_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aseguradora',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
