# Generated by Django 2.0.4 on 2018-05-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_auto_20180430_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ('apodo',)},
        ),
    ]
