# Generated by Django 2.0.4 on 2018-05-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_auto_20180502_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ('nombre',)},
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='apodo',
            new_name='nombre',
        ),
    ]
