# Generated by Django 2.0.4 on 2018-05-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_auto_20180511_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_serie',
            field=models.IntegerField(unique=True),
        ),
    ]
