# Generated by Django 2.0.4 on 2018-05-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_auto_20180514_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='numero',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
