# Generated by Django 2.0.4 on 2018-10-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0011_auto_20180514_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_serie',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
