# Generated by Django 2.0.4 on 2018-05-02 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0005_auto_20180430_1831'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.TextField()),
                ('asunto', models.TextField()),
                ('salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('llegada_aproximada', models.DateTimeField(default=django.utils.timezone.now)),
                ('llegada_real', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('Llegada', 'Llegada'), ('Salida', 'Salida')], max_length=10)),
                ('kilometraje', models.IntegerField(blank=True, null=True)),
                ('limpieza', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('luces_bajas_delanteras', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('aceite_motor', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('liquido_frenos', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('refrigerante', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('indicador_cobustible', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('indicador_temperatura', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('indicador_aceite', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('limpiaparabrisas', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('gato_hidrauilico', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('llave_birlos', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('llanta_refraccion', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('golpes_raspaduras', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('presion_llantas', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('bocina', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pesimo', 'Pesimo')], max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.Reservacion')),
            ],
        ),
    ]
