# Generated by Django 2.0.4 on 2018-05-02 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0003_auto_20180502_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Vehiculo'),
        ),
    ]
