# Generated by Django 2.0.4 on 2018-05-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0006_auto_20180502_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='momento',
            field=models.CharField(choices=[('Salida', 'Salida'), ('Llegada', 'Llegada')], max_length=10),
        ),
    ]
