# Generated by Django 2.0.4 on 2018-05-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0007_auto_20180511_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='es_mantenimiento',
            field=models.BooleanField(default=False),
        ),
    ]
